### ISSUE TITLE
npm package transfer.

### ISSUE THREAD

**Issue by cjoulain** [nwhitmont/stackexchange-node#2]
Hi @nwhitmont,

A user has made a request for a transfer of the `stackexchange-node` package (hosted on npm). We've tried sending an email but the email associated with your npm account is now invalid.

If you agree with this request, please let me know and I'll be happy to do the work on my end.

If you have any other questions, don't hesitate to reach out.

Take care,
CJ

**Comment by nwhitmont** [comment]
@cjoulain what is a transfer?

**Comment by cjoulain** [comment]
Hi @nwhitmont. Thanks for the response!

Another npm user would like to take ownership of this package:
https://www.npmjs.com/package/stackexchange-node

It requires your permission for us to switch the owner from the npm username `nilslikestacos` to the requester's npm username.. If you'd like to hold onto the package to make updates in the near future, we'll leave as is.

If you'd like to transfer ownership of the package to the requester, we can help with that on our end.

**Comment by nwhitmont** [comment]
@cjoulain who is the requestor and are they willing, able, and qualified to maintain the package?

**Comment by cjoulain** [comment]
Hi Nils.

This is their npm user profile:
https://www.npmjs.com/~trott

**Comment by nwhitmont** [comment]
@cjoulain  transfer approved! - I will delete this repo now

**Comment by cjoulain** [comment]
Hi @nwhitmont. Thanks for agreeing to the transfer! Let me know if I should transfer the `stackexchange-node` package over to trott.

**Comment by nwhitmont** [comment]
@cjoulain - yes. do it 👍

**Comment by cjoulain** [comment]
Completed. Thank you, @nwhitmont!
